/* Generated By:JavaCC: Do not edit this line. CALParserTreeConstants.java Version 5.0 */
public interface CALParserTreeConstants
{
  public int JJTPROG = 0;
  public int JJTVOID = 1;
  public int JJTVARDECL = 2;
  public int JJTCONSTDECL = 3;
  public int JJTFUNCTION = 4;
  public int JJTRETURN = 5;
  public int JJTTYPE = 6;
  public int JJTPARAM = 7;
  public int JJTMAIN = 8;
  public int JJTASSIGN = 9;
  public int JJTSTATMENT = 10;
  public int JJTFRETURN = 11;
  public int JJTMINUSOP = 12;
  public int JJTNUMBER = 13;
  public int JJTTRUEOP = 14;
  public int JJTFALSEOP = 15;
  public int JJTPLUSOP = 16;
  public int JJTMINOP = 17;
  public int JJTNEGATE = 18;
  public int JJTCOMPARISON = 19;
  public int JJTORCOND = 20;
  public int JJTANDCOND = 21;
  public int JJTEQCOMP = 22;
  public int JJTNOTEQCOMP = 23;
  public int JJTLTCOMP = 24;
  public int JJTLTEQCOMP = 25;
  public int JJTGTCOMP = 26;
  public int JJTGTEQCOMP = 27;
  public int JJTARGLST = 28;
  public int JJTIDENT = 29;


  public String[] jjtNodeName = {
    "PROG",
    "void",
    "VARDECL",
    "CONSTDECL",
    "FUNCTION",
    "RETURN",
    "TYPE",
    "PARAM",
    "MAIN",
    "ASSIGN",
    "STATMENT",
    "FRETURN",
    "MINUSOP",
    "NUMBER",
    "TRUEOP",
    "FALSEOP",
    "PLUSOP",
    "MINOP",
    "NEGATE",
    "COMPARISON",
    "ORCOND",
    "ANDCOND",
    "EQComp",
    "NOTEQComp",
    "LTComp",
    "LTEQComp",
    "GTComp",
    "GTEQComp",
    "ARGLST",
    "IDENT",
  };
}
/* JavaCC - OriginalChecksum=7feb68ad35da53d129fd6695782b2c96 (do not edit this line) */
