/* Generated By:JavaCC: Do not edit this line. CALParserVisitor.java Version 5.0 */
public interface CALParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(PROG node, Object data);
  public Object visit(VARDECL node, Object data);
  public Object visit(CONSTDECL node, Object data);
  public Object visit(FUNCTION node, Object data);
  public Object visit(RETURN node, Object data);
  public Object visit(TYPE node, Object data);
  public Object visit(PARAM node, Object data);
  public Object visit(MAIN node, Object data);
  public Object visit(ASSIGN node, Object data);
  public Object visit(STATMENT node, Object data);
  public Object visit(FRETURN node, Object data);
  public Object visit(MINUSOP node, Object data);
  public Object visit(NUMBER node, Object data);
  public Object visit(TRUEOP node, Object data);
  public Object visit(FALSEOP node, Object data);
  public Object visit(PLUSOP node, Object data);
  public Object visit(MINOP node, Object data);
  public Object visit(NEGATE node, Object data);
  public Object visit(COMPARISON node, Object data);
  public Object visit(ORCOND node, Object data);
  public Object visit(ANDCOND node, Object data);
  public Object visit(EQComp node, Object data);
  public Object visit(NOTEQComp node, Object data);
  public Object visit(LTComp node, Object data);
  public Object visit(LTEQComp node, Object data);
  public Object visit(GTComp node, Object data);
  public Object visit(GTEQComp node, Object data);
  public Object visit(ARGLST node, Object data);
  public Object visit(IDENT node, Object data);
}
/* JavaCC - OriginalChecksum=283d3e54812b70b8ebead96aa10662b0 (do not edit this line) */
