/* Generated By:JJTree: Do not edit this line. COMPARISON.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class COMPARISON extends SimpleNode {
  public COMPARISON(int id) {
    super(id);
  }

  public COMPARISON(CALParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CALParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8a4a2df57105483b73e9d6eb9c16b925 (do not edit this line) */
