/* Generated By:JJTree: Do not edit this line. CONSTDECL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CONSTDECL extends SimpleNode {
  public CONSTDECL(int id) {
    super(id);
  }

  public CONSTDECL(CALParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CALParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=647940732b138d4db4ff3432345f43f2 (do not edit this line) */
