/* Generated By:JJTree: Do not edit this line. FUNCTION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class FUNCTION extends SimpleNode {
  public FUNCTION(int id) {
    super(id);
  }

  public FUNCTION(CALParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CALParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2f840aadd4ad794fcafa3eeee2e6aba8 (do not edit this line) */
