/* Generated By:JJTree: Do not edit this line. GTEQComp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class GTEQComp extends SimpleNode {
  public GTEQComp(int id) {
    super(id);
  }

  public GTEQComp(CALParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CALParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c7a60bb50d68924dd8ec682223968a2b (do not edit this line) */
