/* Generated By:JJTree: Do not edit this line. PLUSOP.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class PLUSOP extends SimpleNode {
  public PLUSOP(int id) {
    super(id);
  }

  public PLUSOP(CALParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CALParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=557a1b2e1de803a59b88aa7d013a69ac (do not edit this line) */
