/* Generated By:JJTree: Do not edit this line. TRUEOP.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class TRUEOP extends SimpleNode {
  public TRUEOP(int id) {
    super(id);
  }

  public TRUEOP(CALParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CALParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=31333a3e6b091e1ed3a9c39bcff1c258 (do not edit this line) */
